In [10]:
import cobra

In [11]:
path = '/Users/karthik/Desktop/PHCCO IISc Internship/EMT/MODEL1602080000_url.xml'

model = cobra.io.read_sbml_model(path)

Model does not contain SBML fbc package information.
SBML package 'layout' not supported by cobrapy, information is not parsed
SBML package 'render' not supported by cobrapy, information is not parsed
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_10fthf5glu_c "10-formyltetrahydrofolate-[Glu](5)">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_10fthf5glu_c "10-formyltetrahydrofolate-[Glu](5)">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_10fthf5glu_l "10-formyltetrahydrofolate-[Glu](5)">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_10fthf5glu_l "10-formyltetrahydrofolate-[Glu](5)">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_10fthf5glu_m "10-formyltetrahydrofolate-[Glu](5)">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_10fthf5glu_m "10-formyltetrahydrofolate-[Glu](5)">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_10fthf6glu_c "10-formyltetrahydrofolate-[Glu](6)">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_10fthf6glu_c "10-formyltetrahydrofolate-[Glu](6)">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_10fthf6glu_l "10-formyltetrahydrofolate-[Glu](6)">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_10fthf6glu_l "10-formyltetrahydrofolate-[Glu](6)">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_10fthf6glu_m "10-formyltetrahydrofolate-[Glu](6)">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_10fthf6glu_m "10-formyltetrahydrofolate-[Glu](6)">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_10fthf7glu_c "10-formyltetrahydrofolate-[Glu](7)">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_10fthf7glu_c "10-formyltetrahydrofolate-[Glu](7)">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_10fthf7glu_l "10-formyltetrahydrofolate-[Glu](7)">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_10fthf7glu_l "10-formyltetrahydrofolate-[Glu](7)">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_10fthf7glu_m "10-formyltetrahydrofolate-[Glu](7)">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_10fthf7glu_m "10-formyltetrahydrofolate-[Glu](7)">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_10fthf_c "10-Formyltetrahydrofolate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_10fthf_c "10-Formyltetrahydrofolate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_10fthf_l "10-Formyltetrahydrofolate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_10fthf_l "10-Formyltetrahydrofolate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_10fthf_m "10-Formyltetrahydrofolate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_10fthf_m "10-Formyltetrahydrofolate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_13dampp_c "trimethylenediaminium">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_13dampp_c "trimethylenediaminium">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_h2o_c "Water">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_h2o_c "Water">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_o2_c "O2">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_o2_c "O2">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_bamppald_c "beta-Aminopropion aldehyde">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_bamppald_c "beta-Aminopropion aldehyde">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_h2o2_c "Hydrogen peroxide">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_h2o2_c "Hydrogen peroxide">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_nh4_c "Ammonium">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_nh4_c "Ammonium">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_h_m "proton">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_h_m "proton">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_nadph_m "Nicotinamide adenine dinucleotide phosphate - reduced">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_nadph_m "Nicotinamide adenine dinucleotide phosphate - reduced">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_o2_m "O2">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_o2_m "O2">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_h2o_m "Water">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_h2o_m "Water">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_nadp_m "Nicotinamide adenine dinucleotide phosphate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_nadp_m "Nicotinamide adenine dinucleotide phosphate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_atp_c "ATP">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_atp_c "ATP">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_adp_c "ADP">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_adp_c "ADP">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_h_c "proton">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_h_c "proton">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_pi_c "hydrogenphosphate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_pi_c "hydrogenphosphate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_1pipdn2c_x "1-piperideine-2-carboxylate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_1pipdn2c_x "1-piperideine-2-carboxylate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_h_x "proton">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_h_x "proton">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_nadh_x "Nicotinamide adenine dinucleotide - reduced">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_nadh_x "Nicotinamide adenine dinucleotide - reduced">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_Lpipecol_x "L-pipecolic acid">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_Lpipecol_x "L-pipecolic acid">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_nad_x "Nicotinamide adenine dinucleotide">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_nad_x "Nicotinamide adenine dinucleotide">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_25hvitd3_c "calcidiol">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_25hvitd3_c "calcidiol">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_25hvitd3_e "calcidiol">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_25hvitd3_e "calcidiol">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_pyr_c "pyruvate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_pyr_c "pyruvate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_nadph_c "Nicotinamide adenine dinucleotide phosphate - reduced">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_nadph_c "Nicotinamide adenine dinucleotide phosphate - reduced">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_paps_c "(2R,3S,4R,5R)-5-(6-amino-9H-purin-9-yl)-4-hydroxy-2-({[(sulfonatooxy)phosphinato]oxy}methyl)oxolan-3-yl phosphate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_paps_c "(2R,3S,4R,5R)-5-(6-amino-9H-purin-9-yl)-4-hydroxy-2-({[(sulfonatooxy)phosphinato]oxy}methyl)oxolan-3-yl phosphate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_nadp_c "Nicotinamide adenine dinucleotide phosphate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_nadp_c "Nicotinamide adenine dinucleotide phosphate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_pap_c "adenosine 3',5'-bismonophosphate(4-)">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_pap_c "adenosine 3',5'-bismonophosphate(4-)">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_L2aadp_c "L-2-aminoadipate(1-)">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_L2aadp_c "L-2-aminoadipate(1-)">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_akg_m "2-Oxoglutarate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_akg_m "2-Oxoglutarate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_L2aadp_m "L-2-aminoadipate(1-)">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_L2aadp_m "L-2-aminoadipate(1-)">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_akg_c "2-Oxoglutarate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_akg_c "2-Oxoglutarate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_2dr1p_c "2-Deoxy-D-ribose 1-phosphate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_2dr1p_c "2-Deoxy-D-ribose 1-phosphate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_drib_c "2-deoxy-D-ribose">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_drib_c "2-deoxy-D-ribose">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_2hb_c "2-Hydroxybutyrate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_2hb_c "2-Hydroxybutyrate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_nad_c "Nicotinamide adenine dinucleotide">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_nad_c "Nicotinamide adenine dinucleotide">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_2obut_c "2-Oxobutanoate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_2obut_c "2-Oxobutanoate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_nadh_c "Nicotinamide adenine dinucleotide - reduced">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_nadh_c "Nicotinamide adenine dinucleotide - reduced">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_2hb_e "2-Hydroxybutyrate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_2hb_e "2-Hydroxybutyrate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_h_e "proton">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_h_e "proton">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_hco3_e "Bicarbonate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_hco3_e "Bicarbonate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_na1_e "Sodium">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_na1_e "Sodium">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_hco3_c "Bicarbonate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_hco3_c "Bicarbonate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_na1_c "Sodium">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_na1_c "Sodium">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_2oxoadp_m "2-oxoadipate(2-)">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_2oxoadp_m "2-oxoadipate(2-)">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_coa_m "Coenzyme A">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_coa_m "Coenzyme A">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_nad_m "Nicotinamide adenine dinucleotide">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_nad_m "Nicotinamide adenine dinucleotide">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_co2_m "carbon dioxide">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_co2_m "carbon dioxide">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_glutcoa_m "glutaryl-CoA(5-)">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_glutcoa_m "glutaryl-CoA(5-)">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_nadh_m "Nicotinamide adenine dinucleotide - reduced">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_nadh_m "Nicotinamide adenine dinucleotide - reduced">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_2oxoadp_c "2-oxoadipate(2-)">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_2oxoadp_c "2-oxoadipate(2-)">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_34dhmald_c "3,4-Dihydroxymandelaldehyde">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_34dhmald_c "3,4-Dihydroxymandelaldehyde">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_34dhpha_c "(3,4-dihydroxyphenyl)acetate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_34dhpha_c "(3,4-dihydroxyphenyl)acetate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_amet_c "S-Adenosyl-L-methionine">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_amet_c "S-Adenosyl-L-methionine">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_ahcys_c "S-Adenosyl-L-homocysteine">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_ahcys_c "S-Adenosyl-L-homocysteine">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_34dhphe_e "L-dopa">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_34dhphe_e "L-dopa">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_34dhphe_c "L-dopa">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_34dhphe_c "L-dopa">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_34dhpac_c "3,4-Dihydroxyphenylacetaldehyde">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_34dhpac_c "3,4-Dihydroxyphenylacetaldehyde">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_34dhoxmand_c "3,4-Dihydroxymandelate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_34dhoxmand_c "3,4-Dihydroxymandelate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_34hpp_c "3-(4-hydroxyphenyl)pyruvate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_34hpp_c "3-(4-hydroxyphenyl)pyruvate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_co2_c "carbon dioxide">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_co2_c "carbon dioxide">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_hgentis_c "homogentisate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_hgentis_c "homogentisate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_35cgmp_c "3',5'-cyclic GMP(1-)">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_35cgmp_c "3',5'-cyclic GMP(1-)">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_35cgmp_n "3',5'-cyclic GMP(1-)">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_35cgmp_n "3',5'-cyclic GMP(1-)">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_2mop_m "2-methyl-3-oxopropanoate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_2mop_m "2-methyl-3-oxopropanoate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_glu_L_m "L-glutamate(1-)">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_glu_L_m "L-glutamate(1-)">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_3dsphgn_c "(2S)-1-hydroxy-3-oxooctadecan-2-aminium">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_3dsphgn_c "(2S)-1-hydroxy-3-oxooctadecan-2-aminium">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_sphgn_c "sphinganine(1+)">

In [9]:
model

NameError: name 'model' is not defined

In [50]:
model_summary = model.summary()
model_summary

In [51]:
model_summary.to_frame().to_csv('model_summary.csv')

FBA

In [38]:
solution = model.optimize()
solution

In [44]:
solution.to_frame().to_csv('FBA.csv')

In [52]:
single_gene_deletion_results = cobra.flux_analysis.single_gene_deletion(model)
single_gene_deletion_results

            ids  growth   status
0       {440.3}   0.101  optimal
1      {4843.2}   0.101  optimal
2      {2027.1}   0.101  optimal
3       {766.1}   0.101  optimal
4      {8992.1}   0.101  optimal
...         ...     ...      ...
1597   {2875.1}   0.101  optimal
1598    {114.1}   0.101  optimal
1599   {5331.1}   0.101  optimal
1600   {1544.1}   0.101  optimal
1601  {10195.2}   0.101  optimal

[1602 rows x 3 columns]

In [46]:
single_gene_deletion_results.to_csv('single_gene_deletion_results.csv')

In [53]:
single_reaction_deletion_results = cobra.flux_analysis.single_reaction_deletion(model)
single_reaction_deletion_results

                            ids  growth   status
0     {EX_glc_LPAREN_e_RPAREN_}   0.101  optimal
1                       {ITPtn}   0.101  optimal
2                       {FPGS5}   0.101  optimal
3                      {CHOLtu}   0.101  optimal
4                       {r0547}   0.101  optimal
...                         ...     ...      ...
2848                     {CDSm}   0.101  optimal
2849                    {PYDXK}   0.101  optimal
2850                   {CITRtm}   0.101  optimal
2851                   {SARDHm}   0.101  optimal
2852                    {CYSTA}   0.101  optimal

[2853 rows x 3 columns]

In [54]:
single_reaction_deletion_results.to_csv('single_reaction_deletion_results.csv')

DONT DO THIS SHIT FROM HERE. TAKEN TON OF TIME

In [ ]:
double_gene_deletion_results = cobra.flux_analysis.double_gene_deletion(model)
double_gene_deletion_results

In [ ]:
double_gene_deletion_results.to_csv('double_gene_deletion_results.csv')

In [ ]:
double_reaction_deletion_results = cobra.flux_analysis.double_reaction_deletion(model)
double_reaction_deletion_results

In [ ]:
double_reaction_deletion_results.to_csv('double_reaction_deletion_results.csv')

In [1]:
import cobra

# Load a COBRA model (replace 'model.xml' with your actual model file)
model = cobra.io.read_sbml_model('/Users/karthik/Desktop/PHCCO IISc Internship/EMT/MODEL1602080000_url.xml')

# Dictionary to store reaction groups by subsystem
subsystem_groups = {}

# Populate the subsystem_groups dictionary
for reaction in model.reactions:
    subsystem = reaction.subsystem
    if subsystem not in subsystem_groups:
        subsystem_groups[subsystem] = []
    subsystem_groups[subsystem].append(reaction.id)

# Print all reaction groups
for subsystem, reactions in subsystem_groups.items():
    print(f"Subsystem: {subsystem}")
    print(f"Reactions: {', '.join(reactions)}")
    print()

# Example: Print all metabolite groups based on compartments
compartment_groups = {}
for metabolite in model.metabolites:
    compartment = metabolite.compartment
    if compartment not in compartment_groups:
        compartment_groups[compartment] = []
    compartment_groups[compartment].append(metabolite.id)

# Print all metabolite groups
for compartment, metabolites in compartment_groups.items():
    print(f"Compartment: {compartment}")
    print(f"Metabolites: {', '.join(metabolites)}")
    print()

# Example: Print all gene groups based on gene associations
gene_groups = {}
for reaction in model.reactions:
    for gene in reaction.genes:
        gene_id = gene.id
        if gene_id not in gene_groups:
            gene_groups[gene_id] = []
        gene_groups[gene_id].append(reaction.id)

# Print all gene groups
for gene_id, reactions in gene_groups.items():
    print(f"Gene: {gene_id}")
    print(f"Reactions: {', '.join(reactions)}")
    print()

Model does not contain SBML fbc package information.
SBML package 'layout' not supported by cobrapy, information is not parsed
SBML package 'render' not supported by cobrapy, information is not parsed
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_10fthf5glu_c "10-formyltetrahydrofolate-[Glu](5)">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_10fthf5glu_c "10-formyltetrahydrofolate-[Glu](5)">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_10fthf5glu_l "10-formyltetrahydrofolate-[Glu](5)">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_10fthf5glu_l "10-formyltetrahydrofolate-[Glu](5)">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_10fthf5glu_m "10-formyltetrahydrofolate-[Glu](5)">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_10fthf5glu_m "10-formyltetrahydrofolate-[Glu](5)">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_10fthf6glu_c "10-formyltetrahydrofolate-[Glu](6)">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_10fthf6glu_c "10-formyltetrahydrofolate-[Glu](6)">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_10fthf6glu_l "10-formyltetrahydrofolate-[Glu](6)">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_10fthf6glu_l "10-formyltetrahydrofolate-[Glu](6)">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_10fthf6glu_m "10-formyltetrahydrofolate-[Glu](6)">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_10fthf6glu_m "10-formyltetrahydrofolate-[Glu](6)">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_10fthf7glu_c "10-formyltetrahydrofolate-[Glu](7)">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_10fthf7glu_c "10-formyltetrahydrofolate-[Glu](7)">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_10fthf7glu_l "10-formyltetrahydrofolate-[Glu](7)">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_10fthf7glu_l "10-formyltetrahydrofolate-[Glu](7)">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_10fthf7glu_m "10-formyltetrahydrofolate-[Glu](7)">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_10fthf7glu_m "10-formyltetrahydrofolate-[Glu](7)">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_10fthf_c "10-Formyltetrahydrofolate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_10fthf_c "10-Formyltetrahydrofolate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_10fthf_l "10-Formyltetrahydrofolate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_10fthf_l "10-Formyltetrahydrofolate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_10fthf_m "10-Formyltetrahydrofolate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_10fthf_m "10-Formyltetrahydrofolate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_13dampp_c "trimethylenediaminium">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_13dampp_c "trimethylenediaminium">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_h2o_c "Water">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_h2o_c "Water">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_o2_c "O2">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_o2_c "O2">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_bamppald_c "beta-Aminopropion aldehyde">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_bamppald_c "beta-Aminopropion aldehyde">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_h2o2_c "Hydrogen peroxide">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_h2o2_c "Hydrogen peroxide">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_nh4_c "Ammonium">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_nh4_c "Ammonium">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_h_m "proton">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_h_m "proton">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_nadph_m "Nicotinamide adenine dinucleotide phosphate - reduced">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_nadph_m "Nicotinamide adenine dinucleotide phosphate - reduced">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_o2_m "O2">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_o2_m "O2">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_h2o_m "Water">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_h2o_m "Water">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_nadp_m "Nicotinamide adenine dinucleotide phosphate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_nadp_m "Nicotinamide adenine dinucleotide phosphate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_atp_c "ATP">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_atp_c "ATP">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_adp_c "ADP">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_adp_c "ADP">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_h_c "proton">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_h_c "proton">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_pi_c "hydrogenphosphate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_pi_c "hydrogenphosphate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_1pipdn2c_x "1-piperideine-2-carboxylate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_1pipdn2c_x "1-piperideine-2-carboxylate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_h_x "proton">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_h_x "proton">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_nadh_x "Nicotinamide adenine dinucleotide - reduced">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_nadh_x "Nicotinamide adenine dinucleotide - reduced">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_Lpipecol_x "L-pipecolic acid">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_Lpipecol_x "L-pipecolic acid">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_nad_x "Nicotinamide adenine dinucleotide">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_nad_x "Nicotinamide adenine dinucleotide">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_25hvitd3_c "calcidiol">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_25hvitd3_c "calcidiol">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_25hvitd3_e "calcidiol">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_25hvitd3_e "calcidiol">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_pyr_c "pyruvate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_pyr_c "pyruvate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_nadph_c "Nicotinamide adenine dinucleotide phosphate - reduced">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_nadph_c "Nicotinamide adenine dinucleotide phosphate - reduced">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_paps_c "(2R,3S,4R,5R)-5-(6-amino-9H-purin-9-yl)-4-hydroxy-2-({[(sulfonatooxy)phosphinato]oxy}methyl)oxolan-3-yl phosphate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_paps_c "(2R,3S,4R,5R)-5-(6-amino-9H-purin-9-yl)-4-hydroxy-2-({[(sulfonatooxy)phosphinato]oxy}methyl)oxolan-3-yl phosphate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_nadp_c "Nicotinamide adenine dinucleotide phosphate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_nadp_c "Nicotinamide adenine dinucleotide phosphate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_pap_c "adenosine 3',5'-bismonophosphate(4-)">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_pap_c "adenosine 3',5'-bismonophosphate(4-)">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_L2aadp_c "L-2-aminoadipate(1-)">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_L2aadp_c "L-2-aminoadipate(1-)">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_akg_m "2-Oxoglutarate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_akg_m "2-Oxoglutarate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_L2aadp_m "L-2-aminoadipate(1-)">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_L2aadp_m "L-2-aminoadipate(1-)">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_akg_c "2-Oxoglutarate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_akg_c "2-Oxoglutarate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_2dr1p_c "2-Deoxy-D-ribose 1-phosphate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_2dr1p_c "2-Deoxy-D-ribose 1-phosphate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_drib_c "2-deoxy-D-ribose">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_drib_c "2-deoxy-D-ribose">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_2hb_c "2-Hydroxybutyrate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_2hb_c "2-Hydroxybutyrate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_nad_c "Nicotinamide adenine dinucleotide">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_nad_c "Nicotinamide adenine dinucleotide">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_2obut_c "2-Oxobutanoate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_2obut_c "2-Oxobutanoate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_nadh_c "Nicotinamide adenine dinucleotide - reduced">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_nadh_c "Nicotinamide adenine dinucleotide - reduced">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_2hb_e "2-Hydroxybutyrate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_2hb_e "2-Hydroxybutyrate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_h_e "proton">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_h_e "proton">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_hco3_e "Bicarbonate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_hco3_e "Bicarbonate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_na1_e "Sodium">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_na1_e "Sodium">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_hco3_c "Bicarbonate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_hco3_c "Bicarbonate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_na1_c "Sodium">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_na1_c "Sodium">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_2oxoadp_m "2-oxoadipate(2-)">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_2oxoadp_m "2-oxoadipate(2-)">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_coa_m "Coenzyme A">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_coa_m "Coenzyme A">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_nad_m "Nicotinamide adenine dinucleotide">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_nad_m "Nicotinamide adenine dinucleotide">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_co2_m "carbon dioxide">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_co2_m "carbon dioxide">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_glutcoa_m "glutaryl-CoA(5-)">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_glutcoa_m "glutaryl-CoA(5-)">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_nadh_m "Nicotinamide adenine dinucleotide - reduced">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_nadh_m "Nicotinamide adenine dinucleotide - reduced">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_2oxoadp_c "2-oxoadipate(2-)">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_2oxoadp_c "2-oxoadipate(2-)">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_34dhmald_c "3,4-Dihydroxymandelaldehyde">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_34dhmald_c "3,4-Dihydroxymandelaldehyde">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_34dhpha_c "(3,4-dihydroxyphenyl)acetate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_34dhpha_c "(3,4-dihydroxyphenyl)acetate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_amet_c "S-Adenosyl-L-methionine">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_amet_c "S-Adenosyl-L-methionine">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_ahcys_c "S-Adenosyl-L-homocysteine">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_ahcys_c "S-Adenosyl-L-homocysteine">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_34dhphe_e "L-dopa">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_34dhphe_e "L-dopa">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_34dhphe_c "L-dopa">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_34dhphe_c "L-dopa">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_34dhpac_c "3,4-Dihydroxyphenylacetaldehyde">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_34dhpac_c "3,4-Dihydroxyphenylacetaldehyde">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_34dhoxmand_c "3,4-Dihydroxymandelate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_34dhoxmand_c "3,4-Dihydroxymandelate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_34hpp_c "3-(4-hydroxyphenyl)pyruvate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_34hpp_c "3-(4-hydroxyphenyl)pyruvate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_co2_c "carbon dioxide">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_co2_c "carbon dioxide">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_hgentis_c "homogentisate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_hgentis_c "homogentisate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_35cgmp_c "3',5'-cyclic GMP(1-)">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_35cgmp_c "3',5'-cyclic GMP(1-)">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_35cgmp_n "3',5'-cyclic GMP(1-)">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_35cgmp_n "3',5'-cyclic GMP(1-)">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_2mop_m "2-methyl-3-oxopropanoate">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_2mop_m "2-methyl-3-oxopropanoate">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_glu_L_m "L-glutamate(1-)">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_glu_L_m "L-glutamate(1-)">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_3dsphgn_c "(2S)-1-hydroxy-3-oxooctadecan-2-aminium">
Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_3dsphgn_c "(2S)-1-hydroxy-3-oxooctadecan-2-aminium">
Use of CHARGE in the notes element is discouraged, use fbc:charge instead: <Species M_sphgn_c "sphinganine(1+)">

Subsystem: Transport, lysosomal
Reactions: 10FTHF7GLUtl, 10FTHFtl, 7DHFtl, 7THFtl, ACGAMtly, ACNAMlt, ATPasel, COAtl, DHFtl, DIGALSIDEtl, DPCOAtl, FUCtly, GALSIDEtl, GALtly, GLCURtly, GLUt7l, H2Otly, HAtly, KSII_CORE2tly, KSII_CORE4tly, KSItly, MANtly, N2M2NMASNtly, S2L2FN2M2MASNtly, SGALSIDEtl, SO4tl, THFtl, UDPACGALtl, UDPtl, r0984, r1150, r1298, r1299

Subsystem: Transport, mitochondrial
Reactions: 10FTHF7GLUtm, 10FTHFtm, 3MOBt2im, 3MOPt2im, 3SALAASPm, 4ABUTtm, 4MOPt2im, 7DHFtm, 7THFtm, AACTtm, ACACt2m, ACALDtm, ACETONEt2m, ACRNtm, ADNtm, AKGMALtm, AMETt2m, ARGtm, ASNtm, ASPGLUm, ATPtm, BALAtmr, CDPDAGtm, CHSTEROLt1, CHSTEROLt2, CITRtm, CITtam, CITtbm, COAtm, CRNtim, CYTDtm, DGSNtm, DMGtm, DNDPt10m, DNDPt11m, DNDPt12m, DNDPt13m, DNDPt14m, DNDPt15m, DNDPt16m, DNDPt17m, DNDPt18m, DNDPt19m, DNDPt1m, DNDPt20m, DNDPt21m, DNDPt22m, DNDPt23m, DNDPt24m, DNDPt25m, DNDPt26m, DNDPt27m, DNDPt28m, DNDPt29m, DNDPt2m, DNDPt30m, DNDPt31m, DNDPt32m, DNDPt33m, DNDPt34m, DNDPt35m, DNDPt36m, DNDPt37m, DNDPt38m, DNDPt39m, DNDPt3m, DNDPt40m, DNDPt41m, DNDPt42m, DNDPt43m, DNDPt44m, DNDPt45m, DNDPt46m, DNDPt47m, DNDPt48m, DNDPt49m, DNDPt4m, DNDPt50m, DNDPt57m, DNDPt58m, DNDPt59m, DNDPt5m, DNDPt60m, DNDPt61m, DNDPt62m, DNDPt63m, DNDPt6m, DNDPt7m, DNDPt8m, DNDPt9m, FALDtm, FORt2m, FUMSO3tm, FUMSO4tm, FUMtm, FUMTSULtm, GLNtm, GLUt2m, GLYBtm, GLYCtm, GLYtm, HMGCOAtm, Htm, ILEt5m, LEUt5m, LYStm, MALSO3tm, MALSO4tm, MALtm, MALTSULtm, O2Stm, O2tm, ORNt3m, ORNt4m, PCFLOPm, PE_HStm, PSFLIPm, PYRt2m, SARCStm, SUCCt2m, THFtm, THYMDtm, Uritm, VALt5m, XOL27OHtm, r0801, r0819, r0821, r0822, r0829, r0830, r0834, r0835, r0836, r0885, r0907, r0911, r0913, r0915, r0917, r0926, r0941, r0962, r0973, r1020, r1155, r1435, r1454, r2371, r2372, r2373, r2374, r2375, r2376, r2377, r2378, r2379, r2380, r2381, r2382, r2384, r2385, r2386, r2387, r2388, r2389, r2390, r2391, r2392, r2393, r2394, r2419, r2420, r2425, r2433, r2434, r2435, r2437, r2472, r2520, r2539, C4tmc, 3AIB_Dtm, GLU5SAtmc, GLYC3Ptmc, q10h2tc, q10tm

Subsystem: beta-Alanine metabolism
Reactions: 13DAMPPOX, ABUTD, APAT2rm, BAMPPALDOX, NBAHH_ir, PRPNCOAHYDm, SPMDOX, r0283

Subsystem: Lysine metabolism
Reactions: 1PPDCRp, 2AMADPTm, 2OXOADOXm, AATAi, LPCOXp, LYSOXp, PPD2CSPp, SACCD3m, SACCD4m, r0450, r0525, r0594, RE1254C

Subsystem: Transport, extracellular
Reactions: 25HVITD3t, 25HVITD3tin, 2HBt2, 2HCO3_NAt, 34DHPHEt, 5MTHFt, 5MTHFt2, ABUTt2r, ABUTt4_2_r, ACACt2, ADNt, ADRNt, AKGt4_3, ALAASNNaEx, ALACYSNaEx, ALADGLNexR, ALADGLYexR, ALAGLNexR, ALAGLNNaEx, ALAGLYexR, ALASERNaEx, ALAt2r, ALAt4, ALATHRNaEx, ALAtN1, ARACHDt2, ARACHt, ARGLYSex, ARGtiDF, ASCBt4, ASNALANaEx, ASNCYSNaEx, ASNGLNNaEx, ASNSERNaEx, ASNt4, ASNTHRNaEx, ASNtN1, ASPDt6, ASPt6, AVITE1t, BILDGLCURte, BILGLCURte, BTNt2, BTNt3i, BTNt4i, BUTt2r, CAATPS, CAt7r, CGLYt3_2_, CHOLATEt, CHOLATEt3, CHOLtu, CHSTEROLt, CLHCO3tex2, CLOHtex2, CLOXAtex2, CREATt4_2_r, CRNt, CRNtHa, CRNtuNa, CRVNCtr, CYSALANaEx, CYSASNNaEx, CYSGLNNaEx, CYSGLUexR, CYSGLYexR, CYSSERNaEx, CYSt4, CYStec, CYSTGLUex, CYSTHRNaEx, CYSTSERex, CYTDt, CYTDt4, DADNt4, DAGt, DALAt2r, DCYTt, DGSNt, DHAAt1r, DINt, D_LACt2, DLNLCGt, DOPAtu, DOPAVESSEC, DURIt, ELAIDt, ESTRADIOLGLCt, ESTRADIOLGLCt2, ESTRONESt, FATP1t, FATP2t, FATP3t, FATP4t, FATP5t, FATP6t, FATP7t, FATP8t, FATP9t, FOLt2, FRUt1r, FRUt4, GALt1r, GALt4, GCHOLAt3, GCHOLAte, GLCt1r, GLCt4, GLNALANaEx, GLNASNNaEx, GLNCYSNaEx, GLNSERNaEx, GLNt4, GLNTHRNaEx, GLNtN1, GLUt6, GLUVESSEC, GLYt2r, GLYt4, GLYt7_211_r, GSNt, H2Ot, HCO3_CLt, HDCAtr, HDCEAtr, HISt4, HISTAtu, HISTAVESSEC, HIStN1, HOMt4, HYXNt, ILEtec, INSt, INSTt2r, KCC2t, KCCt, KSII_CORE2t, KSII_CORE4t, KSIt, LCTStg, LEUKTRA4t, LEUKTRB4t, LEUKTRD4t, LEUKTRF4t, LEUt4, LEUtec, L_LACt2r, LNLCt, LNLNCAt, LNLNCGt, LPCHOLt, LYSt4, LYStiDF, MANt1r, MANt4, METLEUex, METt4, METtec, N2M2NMASNt, NAHCO3_HCLt, NaKt, NAt3_1, NAt5, NCKt, NCNt, NKCC2t, NKCCt, NRPPHRtu, NRPPHRVESSEC, NRVNCt, O2t, OCDCAtr, OCDCEAtr, ORNtiDF, OXAHCOtex, PCt, PHEMEt, PHEt4, PHEtec, PNTOt5, PRODt2r, PROSTGD2t, PROSTGE1t, PROSTGE1t3, PROSTGE2t, PROSTGE2t2, PROSTGE2t3, PROSTGF2t, PROSTGI2t, PROt2r, PROt4, PYRt2r, RETFAt, RETt, RTOTAL2t, S2L2FN2M2MASNt, SERALANaEx, SERASNNaEx, SERCYSNaEx, SERDGLNexR, SERDGLYexR, SERGLNexR, SERGLNNaEx, SERGLYexR, SERLYSNaex, SERt4, SERTHRNaEx, SO4CLtex2, SO4HCOtex, SO4OXAtex2, SO4t4_2, SRTNtu, STRDNCt, SUCCt4_2, TAURt4_2_r, TCHOLAt, TCHOLAt3, THMt3, THRALANaEx, THRASNNaEx, THRCYSNaEx, THRGLNexR, THRGLNNaEx, THRGLYexR, THRSERNaEx, THRt4, THYOXt, THYOXt2, TRIODTHYt, TRIODTHYt2, TRPt, TTDCAtr, TYRt, UREAt, URIt, VACCt, VALtec, VITD3t, VITD3t2, XOLEST2te, r0813, r0817, r0870, r0879, r0892, r0899, r0942, r0963, r0993, r1044, r1045, r1050, r1090, r1106, r1116, r1143, r1144, r1492, r1495, r1514, r1515, r1516, r1517, r1518, r1519, r1520, r1521, r1522, r1523, r1525, r1527, r1529, r1530, r1540, r1544, r1546, r1547, r1548, r1549, r1551, r1552, r1553, r1554, r1556, r1557, r1559, r1560, r1561, r1562, r1563, r1564, r1565, r1566, r1567, r1568, r1569, r1570, r1571, r1573, r1574, r1575, r1576, r1578, r1579, r1580, r1581, r1583, r1584, r1585, r1586, r1587, r1588, r1589, r1590, r1591, r1592, r1593, r1594, r1595, r1596, r1597, r1598, r1599, r1600, r1602, r1603, r1604, r1605, r1606, r1607, r1608, r1609, r1610, r1611, r1612, r1613, r1614, r1615, r1616, r1617, r1618, r1619, r1620, r1621, r1622, r1623, r1624, r1625, r1626, r1627, r1628, r1629, r1630, r1631, r1632, r1633, r1634, r1635, r1636, r1637, r1638, r1639, r1640, r1641, r1642, r1643, r1644, r1645, r1646, r1647, r1648, r1649, r1650, r1651, r1652, r1653, r1654, r1655, r1656, r1657, r1658, r1659, r1660, r1661, r1662, r1664, r1665, r1666, r1667, r1668, r1669, r1670, r1671, r1672, r1673, r1674, r1675, r1676, r1677, r1678, r1679, r1680, r1681, r1682, r1683, r1684, r1685, r1686, r1687, r1690, r1691, r1692, r1693, r1695, r1696, r1698, r1700, r1701, r1702, r1705, r1706, r1707, r1708, r1710, r1711, r1713, r1715, r1716, r1717, r1720, r1721, r1722, r1723, r1725, r1726, r1728, r1730, r1731, r1732, r1733, r1734, r1735, r1736, r1737, r1738, r1739, r1740, r1741, r1742, r1743, r1744, r1745, r1746, r1747, r1748, r1749, r1750, r1751, r1752, r1753, r1754, r1755, r1756, r1757, r1758, r1759, r1760, r1761, r1762, r1763, r1764, r1765, r1766, r1767, r1768, r1769, r1770, r1771, r1772, r1773, r1774, r1775, r1776, r1777, r1778, r1779, r1780, r1781, r1782, r1783, r1784, r1785, r1786, r1787, r1788, r1789, r1790, r1791, r1792, r1796, r1797, r1798, r1799, r1800, r1801, r1803, r1805, r1806, r1807, r1808, r1809, r1810, r1811, r1812, r1813, r1814, r1815, r1816, r1817, r1818, r1819, r1820, r1821, r1822, r1823, r1824, r1825, r1826, r1827, r1828, r1829, r1830, r1831, r1832, r1833, r1834, r1835, r1836, r1837, r1841, r1842, r1843, r1844, r1846, r1847, r1848, r1850, r1851, r1852, r1853, r1854, r1855, r1856, r1857, r1858, r1859, r1860, r1861, r1862, r1863, r1864, r1865, r1866, r1867, r1871, r1872, r1873, r1874, r1876, r1877, r1879, r1880, r1881, r1882, r1883, r1884, r1885, r1886, r1887, r1888, r1889, r1890, r1891, r1892, r1893, r1894, r1895, r1896, r1897, r1898, r1899, r1900, r1901, r1902, r1903, r1904, r1905, r1906, r1907, r1908, r1909, r1910, r1911, r1912, r1913, r1914, r1915, r1916, r1917, r1918, r1919, r1920, r1921, r1922, r1923, r1924, r1925, r1926, r1928, r1929, r1930, r1931, r1932, r1933, r1934, r1935, r1936, r1937, r1938, r1939, r1940, r1941, r1942, r1943, r1944, r1945, r1946, r1947, r1948, r1949, r1950, r1951, r1952, r1953, r1954, r1955, r1956, r1957, r1958, r1959, r1960, r1961, r1962, r1963, r1964, r1965, r1966, r1967, r1968, r1969, r1970, r1971, r1972, r1973, r1974, r1975, r1976, r1977, r1978, r1979, r1980, r1981, r1982, r1983, r1984, r1985, r1986, r1987, r1988, r1989, r1990, r1991, r2073, r2079, r2080, r2081, r2082, r2083, r2084, r2085, r2086, r2087, r2088, r2089, r2090, r2091, r2092, r2093, r2094, r2095, r2096, r2097, r2098, r2099, r2100, r2101, r2102, r2103, r2104, r2105, r2106, r2107, r2108, r2109, r2110, r2111, r2112, r2113, r2114, r2115, r2116, r2117, r2118, r2119, r2120, r2121, r2122, r2123, r2124, r2125, r2126, r2127, r2128, r2129, r2130, r2131, r2132, r2133, r2150, r2310, r2313, r2314, r2315, r2316, r2317, r2318, r2319, r2320, r2321, r2322, r2323, r2324, r2325, r2326, r2327, r2328, r2329, r2330, r2331, r2332, r2333, r2334, r2335, r2338, r2342, r2344, r2346, r2353, r2354, r2355, r2356, r2357, r2358, r2359, r2360, r2362, r2364, r2365, r2366, r2367, r2368, r2443, r2447, r2465, r2471, r2525, r2526, r2532, r2534, r2535, CITt4_4, HCO3_NAt, INSTt4_2, PIt8, 4OHPROIMINOtc, ALAyLATthc, ASCBSVCTtc, BALABETAtc, BALAPAT1tc, CBLTDe, CBLtle, CYSTALArBATtc, CYSTLEUrBATtc, FOLTle, GLNyLATthc, HISCAT1, HISyLATtc, HISyLATthc, LEUyLAThtc, METyLATthc, NACDe, NACHORCTL3le, ORNALArBATtc, ORNLEUrBATtc, PHEyLATthc, PROIMINOtc, RIBFLVte, TAGHSTDe, TAUBETAtc, TAUPAT1c, THMATPe, VITEtl, 3HCO3_NAt, 4HPROLTASCT1, ASPDTDe, ASPPROASCT1, ASPte, BTNt3ile, CHOLESTle, FE2DMT1, FE3MTP1, FMNALKPle, GLUPROASCT1, GSNt5le, NODe, PHEMEe, PNTOt5le, PRO_Dtde, 4MOPte, 5OXPROt, MAL_Lte, PNTOte

Subsystem: Pyrimidine catabolism
Reactions: 2DR1PP, BUP2, CYTD, DCMPDA, DCYTD, DHPM1, DHPM2, DURAD, DURAD2, NTD1, NTD2, NTD3, NTD4, NTD5, PYNP2r, TMDPP, UPPN, r0330, r0377, r0483

Subsystem: Tryptophan metabolism
Reactions: 2OXOADPTm, 3HAO, 3HKYNAKGAT, 5HOXINDACTO2OX, ACACT1r, ACACT1rm, AMCOXO, ECOAH1m, FKYNH, GLUTCOADHm, HACD1m, HKYNH, KYN3OX, KYNAKGAT, KYNATESYN, MELATNOX, PCLAD, TRPO2, r0541, r0645, r0647, r0758, RE1233C, RE2349C, RE2426C

Subsystem: Tyrosine metabolism
Reactions: 34DHPLACOX, 34DHPLACOX_NADP_, 34DHXMANDACOX, 34DHXMANDACOX_NADP_, 34HPPOR, 3MOX4HOXPGALDOX, 3MOX4HOXPGALDOX_NADP_, FALDH, FUMAC, H2O2syn, HGNTOR, MACACI, SFGTH, TYRTA, RE0908C, RE0912C

Subsystem: Transport, nuclear
Reactions: 35CGMPtn, ACNAMtn, ATPtn, BIOCYTtn, BTNtn, CMPACNAtn, CTPtn, DATPtn, DCTPtn, DGTPtn, DIDPtn, DITPtn, DNADtn, DTDPtn, DTTPtn, DUDPtn, DUMPtn, DURItn, GMPtn, H2O2tn, H2Otn, IDPtn, ITPtn, LYStn, MI14Ptn, MI1P_Dtn, NADtn, NH4tn, NICRNTtn, NMNtn, O2Stn, O2tn, PA_HStn, PAIL_HStn, r1459

Subsystem: Sphingolipid metabolism
Reactions: 3DSPHR, ARSA, DHCRD1, DHCRD2, DSAT, GAL3ST11, GBA, GLAl, SBPP1er, SBPP3er, SERPT, SLCBK1, SMPD3g, SMS, SPHK21c, UGCG, r0787

Subsystem: Valine, leucine, and isoleucine metabolism
Reactions: 3HBCOAHLm, ACACT10m, ACOAD10m, ACOAD8m, ACOAD9m, ECOAH12m, ECOAH9m, HACD9m, HIBDm, ILETA, ILETAm, LEUTA, LEUTAm, MCCCrm, MGCHrm, MMCDm, MMEm, MMMm, MMSAD1m, OCOAT1m, OIVD1m, OIVD2m, OIVD3m, PPCOACm, VALTA, VALTAm, r0560, r0561, r0571, r0603, r0643, r0655, r0669, RE3326M

Subsystem: Methionine and cysteine metabolism
Reactions: 3SALATAi, 3SALATAim, 3SPYRSP, 3SPYRSPm, AHC, CYSTA, CYSTGL, CYSTS, METAT, METS, SULFOX, r0027, r0142, r0210

Subsystem: Arginine and Proline Metabolism
Reactions: 4HGLSDm, ADMDC, AGMTm, ARGDCm, DKMPPD, G5SADrm, MDRPD, MTAP, MTRI, NOS1, NOS2, P5CRm, P5CRxm, PHCDm, PHCHGSm, PRO1xm, PROD2m, PTRCOX1, UNK2, r0145, r0615, r0616, r0617, r0618, r0686, P5CR

Subsystem: Steroid metabolism
Reactions: 5ADTSTSTERONESULT, CHSTEROLSULT, DHEASULT, ESTSULT, HSD11B1r, HSD11B2r, HSD17B1, HSD17B7r, HSD17B9r, HSD3A1r, HSD3B2r, PRGNLONESULT, STS1, STS2, RE1100C, RE1135C

Subsystem: N-glycan degradation
Reactions: A_MANASEly, AHEXASE2ly, AHEXASEly, B_MANNASEly, ENGASE2ly, ENGASEly, FUCASEly, GALASE1ly, GASNASE2ly, GASNASEly, SIAASEly

Subsystem: Propanoate metabolism
Reactions: AACOAT, ACCOAL, ACCOALm, ACS2, ADCim, MMSAD3m, PPCOAOm, r0365, r1154

Subsystem: Glycine, serine, alanine and threonine metabolism
Reactions: AACTOOR, ALASm, AOBUTDsm, BETALDHxm, BHMT, CHOLD2m, DMGDHm, GCC2am, GCC2bim, GCC2cm, GCCam, GCCbim, GCCcm, GHMT2r, GHMT2rm, GLYATm, GNMT, OBDHc, PGCD, PSERT, PSP_L, SPTix, THRD_L, r0295, r0552, r0553

Subsystem: Glutamate metabolism
Reactions: ABTArm, ALATA_L, CBPSam, GLNS, GLUDxm, GLUDym, GLUNm, GTHO, GTHOm, P5CDm, r0178, r0464, r0549

Subsystem: Cholesterol metabolism
Reactions: ACACT1x, C14STRr, C3STDH1Pr, C3STDH1r, C3STKR2r, C4STMO1r, C4STMO2Pr, C4STMO2r, DHCR241r, DHCR242r, DHCR243r, DHCR71r, DHCR72r, DMATT, DMATTx, DPMVDx, EBP1r, EBP2r, GRTT, GRTTx, HMGCOASi, HMGCOASim, HMGLm, HMGLx, IPDDIx, LNSTLSr, LSTO1r, LSTO2r, MEVK1x, P450SCC1m, PMEVKx, SQLEr, SQLSr, r0170, r0321, r0463, r0488, r0575, r0780, r0781, r0783, r1380, r1381, CHOLESACATc

Subsystem: Fatty acid oxidation
Reactions: ACACT4p, ACACT5p, ACACT6p, ACACT7p, ACCOAC, ACCOACm, ACOAO7p, ARACHCPT1, ARACHCPT2, ARACHCRNt, C160CPT1, C160CPT2, C160CRNt, C161CPT1, C161CPT12, C161CPT2, C161CPT22, C161CRN2t, C161CRNt, C180CPT1, C180CPT2, C180CRNt, C181CPT1, C181CPT2, C181CRNt, CSNAT2m, CSNAT2x, CSNAT3x, CSNATer, CSNATm, CSNATp, CSNATr, DMNONCOACRNCPT1, ELAIDCPT1, ELAIDCPT2, ELAIDCRNt, ETF, ETFQO, FACOAL160i, FACOAL161, FACOAL180i, FACOAL1812, FACOAL181i, FACOAL1821, FACOAL1831, FACOAL191, FACOAL200, FACOAL204, FAOXC140, FAOXC160, FAOXC16080m, FAOXC16080x, FAOXC161802m, FAOXC16180m, FAOXC180, FAOXC180x, FAOXC1811601m, FAOXC1811602m, FAOXC1811603m, FAOXC18280m, FAOXC200180m, FAOXC200180x, FAOXC2242046x, FAOXC226205x, FAOXC80, FDH, LCAT1e, LNELDCCPT1, LNELDCCPT2, LNELDCCRNt, MCD, MCDm, PCRNtm, PTE3x, PTE4x, TTDCPT1, TTDCPT2, TTDCRNt, VACCCPT1, VACCCPT2, VACCCRNt, r0287, r0308, r0309, r0310, r0311, r0434, r0437, r0633, r0634, r0636, r0637, r0638, r0639, r0641, r0652, r0653, r0660, r0661, r0714, r0715, r0717, r0718, r0719, r0720, r0721, r0722, r0723, r0724, r0726, r0727, r0728, r0729, r0730, r0731, r0732, r0733, r0734, r0735, r0791, r1252, r1255, r1257, r1260, r1396, r1397, r1401, r1443, r1444, r1445, r1447, r1448, r1449, r1450, r1451, r1487, r1488, RE1518M, RE1519M, RE1521M, RE1526M, RE1533M, RE1573M, RE2759X, RE2998M, RE2999M, RE3000M, RE3001M, RE3003M, RE3004M, RE3005M, RE3006M, RE3074X, RE3079X, RE3624M, RE3626M, ADPACDAc, ADPACTD, ADPCOACROT, ADPCOAPTE, C10DCCACT, C10DCc, C12DCACOT, C12DCACT, C12DCTD, C30CPT1, C40CPT1, C4CRNCPT2, C4DCCACT, C60CPT1, C6DCCACT, C6DCc, C8DCc, FAOXC101C8m, FAOXC101m, FAOXC10C8m, FAOXC10C8x, FAOXC10DCC8DCx, FAOXC121C101m, FAOXC121C10x, FAOXC12C10m, FAOXC12C10x, FAOXC12DCC10DCx, FAOXC12DCTc, FAOXC12DCc, FAOXC12DCx, FAOXC141C121m, FAOXC14C12m, FAOXC14C12x, FAOXC14DCC12DCx, FAOXC161C141m, FAOXC16BRx, FAOXC16C14m, FAOXC16C14x, FAOXC16DCC14DCx, FAOXC16DCr, FAOXC16OHC16r, FAOXC181C161m, FAOXC4C2m, FAOXC4C4DCc, FAOXC6C4m, FAOXC6C4x, FAOXC6DCC4DCx, FAOXC8C6m, FAOXC8C6x, FAOXC8DCC6DCx, FAOXOHC16C16DCc, FAOXTC101TC102m, FAOXTC102C101m, FAOXTC122TC101m, FAOXTC122m, FAOXTC142TC122m, FAOXTC162TC142m, FAOXTC182TC162m, HEXCOAACBP, HEXDIACTD, HEXDICOAACBPx, OCD11COACPT1, OCD11CRNCACT, OCD11CRNCPT2, OCT11EFATP, OMHPALTD, SBCOAACOTx, SEBACACT, SEBACIDTD, SEBCOACROT, SEBCOAPET, SUBEACTD, SUBERCACT, SUBERCROT, SUBERICACT, SUCCACT, SUCCCROT, SUCCOAPET

Subsystem: Transport, peroxisomal
Reactions: ACACtx, ADRNCOAtx, ARACHCOAtx, ARACHDCOAtx, CLPNDCOAtx, COAtp, CRNCAR3tp, CRNCARtp, DCSPTN1COAtx, DGCHOLtx, DHCHOLESTANATEtm, FADH2tx, FADtx, FRDPtr, GLXtp, GLYCLTtp, GLYtp, HPYRtp, IPDPtx, LGNCCOAtx, LYStip, NAtx, NH4tp, NRVNCCOAtx, O2Stx, O2tp, OCCOAtx, PItx, PPItx, PRISTtx, SCP21x, SCP22x, SERtp, SUCCtp, THP2Ctp, TMNDNCCOAtx, r0934, r0954, r0990, r0997, r0999, r1019, r1147, r1148, r1292, r2497, r2499, r2501, r2503, r2516, r2518, C16txc, C2tcx, C4tcx, C4x, C6COAt, C6CRNtcx, C9BRxtc, DCSPTN1COAtxc, LGNCCOAtcx, NRVNCCOAtxc, PRISTCOAtcx, SCP21cx, STCOATxc, LACLt

Subsystem: Transport, endoplasmic reticular
Reactions: ACCOAtr, AHCYStr, AMETr, Asn_X_Ser_Thrtr, ATP1ter, ATP2ter, BILDGLCURtr, CERT1rt, CERT2rt, CHOLtr, CO2ter, ESTRADIOLtr, ESTRONEtr, FADH2tru, FADtru, FORtr, G6Pter, GLCter, H2Oter, MANter, NADPHtru, NADPtru, O2ter, PA_HSter, PIter, SPH1Ptr, SPHGNtr, SPHINGStr, SPHS1Ptr, UDPGLCAter, UDPGLCter, UMPtr, r0840, r0970, r0983, r0989, r0994, r0995, r0998, r1010, r1018, r1051, r2473, r2505, r2509, r2510, r2514, r2519, r2537, r2538, OCDEAFABP1tc, PEHSFABPe, PMTCOAFABP1tc, CHSTEROLtrc, FRDPtcr

Subsystem: Aminosugar metabolism
Reactions: ACGAM2E, ACGAM6PSi, ACGAMK, ACGAMPM, ACNAM9PL, ACNAMPH, ACNMLr, AGDC, AMANK, CMPSAS, CMPSASn, G6PDA, GF6PTA, UAG2EMAi, UAGDP

Subsystem: Glycerophospholipid metabolism
Reactions: ACHEe, CDIPTr, CDS, CDSm, CEPTC, CEPTE, CHAT, CHLP, CHLPCTD, CHOLK, CLS_hs, DAGK_hs, DAGKn_hs, ETHAK, ETHP, GLYK, GLYKm, GPDDA1, LPASE, PAFH, PAFS, PCHOLP_hs, PCHOLPg_hs, PCHOLPm_hs, PCHOLPr_hs, PETHCT, PETOHMm_hs, PETOHMr_hs, PGPP_hs, PGPPT, PI4P5K, PIK4, PLA2_2, PLA2_2e, PSDm_hs, PSSA1_hs, PSSA2_hs, r0245, RE3301C

Subsystem: Citric acid cycle
Reactions: ACITL, ACONT, ACONTm, AKGDm, CITL, CSm, FUM, FUMm, ICDHxm, ICDHy, ICDHyp, ICDHyrm, MDH, MDHm, SUCD1m, SUCOAS1m, SUCOASm, r0081, r0509

Subsystem: Butanoate metabolism
Reactions: ACOAD1fm

Subsystem: Bile acid synthesis
Reactions: ACOX22x, AMACR2p, BAAT3x, CH25H, HSD17B42x, HSD3B7P, P45027A12m, P45027A13m, P45027A15m, P45027A16m, P45027A1m, SCP2x, r0301, r0573, r0650, r0651, r0672, r0688, r0698, r0739, r0797, RE1796M, RE1796R, RE1804M, RE1807M, RE1834C, RE1835C, RE1836X, RE2625M, RE2626C, RE2626M, RE2649C, RE2649M, RE2814M, RE2814R, RE3346C, RE3346M

Subsystem: Vitamin B2 metabolism
Reactions: ACP1_FMN_, FADDP, FMNAT, RBFK, FADDPle, FERO

Subsystem: Glycolysis/gluconeogenesis
Reactions: ACS, ACSm, ACYP, ALDD2x, ALDD2xm, ALDD2y, DPGase, DPGM, ENO, FBA, G3PD2m, G6PPer, GAPD, HEX1, LDH_L, PDHm, PEPCKm, PFK, PGI, PGK, PGM, PGMT, PYK, TPI, r0173, r0354, r0355

Subsystem: Pyruvate metabolism
Reactions: ACTLMO, ACTNMO, ALCD21_D, ALCD21_L, ALCD22_D, ALCD22_L, ALR2, ALR3, GLYOX, LALDO, LALDO2x, LCADi, LCADi_D, LDH_D, LGTHL, L_LACDcm, ME1m, ME2, ME2m, PCm, PPDOx, PPDOy

Subsystem: Purine catabolism
Reactions: ADA, ADAe, NTD11, PUNP2, PUNP3, PUNP4, PUNP5, PUNP6, r0009, r0047, r0119, r0276, r0812, r0860

Subsystem: Nucleotide interconversion
Reactions: ADK1, ADK1m, ADK3, ADK3m, ADKd, ADNCYC, ADNK1, ADPRDP, ADSK, ADSL1, ADSS, AMPDA, ATPH1e, BPNT, BPNT2, CTPS1, CYTDK1, CYTDK2m, CYTK1, CYTK10, CYTK10n, CYTK11, CYTK11n, CYTK12, CYTK12n, CYTK13, CYTK13n, CYTK14, CYTK14n, CYTK1m, CYTK1n, CYTK2, CYTK2n, CYTK3, CYTK3n, CYTK4, CYTK4n, CYTK5, CYTK5n, CYTK6, CYTK6n, CYTK7, CYTK7n, CYTK8, CYTK8n, CYTK9, CYTK9n, DADA, DADAe, DCK1n, DCK2n, DCYTDn, DGK1, DGK2m, DGNSKm, DTMPK, DURIK1, DURIK1m, DURIPP, DUTPDPm, DUTPDPn, GK1, GMPR, GMPS2, GUACYC, IMPD, NDP6, NDP7er, NDP7ex, NDP7g, NDP8, NDP8ex, NDPK1, NDPK10, NDPK10n, NDPK1m, NDPK1n, NDPK2, NDPK2m, NDPK2n, NDPK3, NDPK3m, NDPK3n, NDPK4, NDPK4m, NDPK4n, NDPK5, NDPK5m, NDPK5n, NDPK6, NDPK6m, NDPK6n, NDPK7, NDPK7n, NDPK8, NDPK8m, NDPK8n, NDPK9, NDPK9n, NTD10, NTD1m, NTD2e, NTD2m, NTD5m, NTD6, NTD7, NTD7e, NTD8, NTD9, PDE1, PDE4, PDE4n, PUNP1, PUNP7, RNDR1, RNDR2, RNDR3, RNDR4, SADT, TMDK1, TMDK1m, TMDS, TRDR, TRDRm, UMPK, UMPK2, UMPK2n, UMPK3, UMPK3n, UMPK4, UMPK4n, UMPK5, UMPK5n, UMPK6, UMPK6n, UMPK7, UMPK7n, UMPKm, UMPKn, URIDK2m, r0345, r0394, r0395, r0456, r0470, r0472, r0474, r0475, r0531, r1156

Subsystem: Nucleotide salvage pathway
Reactions: ADPT, GUAPRT, HXPRT

Subsystem: Purine synthesis
Reactions: ADSL2, AICART, AIRCr, GARFT, GLUPRT, IMPC, PRAGSr, PRASCS, PRFGS, r0666

Subsystem: Keratan sulfate synthesis
Reactions: AG13T10g, AG13T11g, AG13T12g, AG13T13g, AG13T14g, AG13T15g, AG13T16g, AG13T17g, AG13T18g, AG13T1g, AG13T2g, AG13T3g, AG13T4g, AG13T5g, AG13T6g, AG13T7g, AG13T8g, AG13T9g, G14T10g, G14T11g, G14T12g, G14T13g, G14T14g, G14T15g, G14T16g, G14T17g, G14T18g, G14T19g, G14T20g, G14T21g, G14T2g, G14T3g, G14T4g, G14T5g, G14T6g, G14T7g, G14T8g, G14T9g, S23T2g, S23T3g, S23T4g, S6T10g, S6T11g, S6T12g, S6T13g, S6T14g, S6T15g, S6T16g, S6T17g, S6T18g, S6T1g, S6T2g, S6T3g, S6T4g, S6T5g, S6T6g, S6T7g, S6T8g, S6T9g

Subsystem: Triacylglycerol synthesis
Reactions: AGPAT1, DGAT, GPAM_hs, LPS, LPS2, LPS3, LPSe, PPAP

Subsystem: Alanine and aspartate metabolism
Reactions: AGTix, ALAR, ARGSL, ARGSS, ASNNm, ASNS1, ASPTA, ASPTAm, r0127

Subsystem: Miscellaneous
Reactions: ALCD1, CATp, H2CO3D, PPAer, PRDX, TRDR2, TRDR3, r0016, RE0383C

Subsystem: Glutathione metabolism
Reactions: AMPTASECG, AMPTASECGe, GGLUCT, GLUCYS, GTHP, GTHPm, GTHS, GTMLTe, OPAHir, r0021, r0022, r0129, r0130, r0568

Subsystem: Biotin metabolism

In [3]:
model.groups

[<Group Transport, lysosomal at 0x307cfa410>,
 <Group Transport, mitochondrial at 0x307d0e0d0>,
 <Group beta-Alanine metabolism at 0x307cfbb90>,
 <Group Lysine metabolism at 0x307d3f9d0>,
 <Group Transport, extracellular at 0x307d3db50>,
 <Group Pyrimidine catabolism at 0x307d00550>,
 <Group Tryptophan metabolism at 0x307d2c090>,
 <Group Tyrosine metabolism at 0x307d2c4d0>,
 <Group Transport, nuclear at 0x307d2e250>,
 <Group Sphingolipid metabolism at 0x307d03150>,
 <Group Valine, leucine, and isoleucine metabolism at 0x307d2e050>,
 <Group Methionine and cysteine metabolism at 0x307d2f190>,
 <Group Arginine and Proline Metabolism at 0x307d2f210>,
 <Group Steroid metabolism at 0x307d2f290>,
 <Group N-glycan degradation at 0x307d2ebd0>,
 <Group Propanoate metabolism at 0x307d2eb10>,
 <Group Glycine, serine, alanine and threonine metabolism at 0x307d2cf50>,
 <Group Glutamate metabolism at 0x307d2ec10>,
 <Group Cholesterol metabolism at 0x307d2d290>,
 <Group Fatty acid oxidation at 0x307d2e690>,
 <Group Transport, peroxisomal at 0x307d2fe50>,
 <Group Transport, endoplasmic reticular at 0x307d2ff10>,
 <Group Aminosugar metabolism at 0x307d2d650>,
 <Group Glycerophospholipid metabolism at 0x307d2ffd0>,
 <Group Citric acid cycle at 0x307d2e850>,
 <Group Butanoate metabolism at 0x307d2f550>,
 <Group Bile acid synthesis at 0x307d2fc10>,
 <Group Vitamin B2 metabolism at 0x307d2dc50>,
 <Group Glycolysis/gluconeogenesis at 0x307d2dcd0>,
 <Group Pyruvate metabolism at 0x307d2d150>,
 <Group Purine catabolism at 0x307d2ff50>,
 <Group Nucleotide interconversion at 0x307d2ced0>,
 <Group Nucleotide salvage pathway at 0x307d2fd90>,
 <Group Purine synthesis at 0x307d2fe10>,
 <Group Keratan sulfate synthesis at 0x307d2fe90>,
 <Group Triacylglycerol synthesis at 0x307d2f610>,
 <Group Alanine and aspartate metabolism at 0x307d2df10>,
 <Group Miscellaneous at 0x307d2de10>,
 <Group Glutathione metabolism at 0x307d2d210>,
 <Group Biotin metabolism at 0x307d2e190>,
 <Group Urea cycle at 0x307d2eed0>,
 <Group Unassigned at 0x307d2ef10>,
 <Group Pyrimidine synthesis at 0x307cdd0d0>,
 <Group Oxidative phosphorylation at 0x307cdfc10>,
 <Group N-glycan synthesis at 0x307cde8d0>,
 <Group ROS detoxification at 0x307cde410>,
 <Group Transport, golgi apparatus at 0x307cde2d0>,
 <Group O-glycan synthesis at 0x307cde210>,
 <Group Taurine and hypotaurine metabolism at 0x307cde190>,
 <Group D-alanine metabolism at 0x307cdc190>,
 <Group Vitamin C metabolism at 0x307cdf190>,
 <Group Fatty acid synthesis at 0x307cdeb50>,
 <Group Pentose phosphate pathway at 0x307cdde50>,
 <Group Folate metabolism at 0x307cdca50>,
 <Group Tetrahydrobiopterin metabolism at 0x307cde610>,
 <Group CoA synthesis at 0x307cdfd10>,
 <Group Keratan sulfate degradation at 0x307cdf410>,
 <Group Exchange/demand reaction at 0x307cdfb90>,
 <Group Fructose and mannose metabolism at 0x307cdc890>,
 <Group Glyoxylate and dicarboxylate metabolism at 0x307cdcc50>,
 <Group Heme synthesis at 0x307cdf990>,
 <Group Galactose metabolism at 0x307cde6d0>,
 <Group Starch and sucrose metabolism at 0x307cdf690>,
 <Group Eicosanoid metabolism at 0x307cdcc90>,
 <Group Hyaluronan metabolism at 0x307cdc610>,
 <Group Histidine metabolism at 0x307cdd910>,
 <Group C5-branched dibasic acid metabolism at 0x307cdf710>,
 <Group CoA catabolism at 0x307cdf0d0>,
 <Group Vitamin A metabolism at 0x307cdee90>,
 <Group Inositol phosphate metabolism at 0x307cdd850>,
 <Group NAD metabolism at 0x307cdeb10>,
 <Group Vitamin B6 metabolism at 0x307cded90>,
 <Group Phenylalanine metabolism at 0x307cdf4d0>,
 <Group Thiamine metabolism at 0x307d14a50>,
 <Group Cysteine Metabolism at 0x307d16750>,
 <Group Phosphatidylinositol phosphate metabolism at 0x307d169d0>,
 <Group Glycosphingolipid metabolism at 0x307d16150>,
 <Group Androgen and estrogen synthesis and metabolism at 0x307d172d0>,
 <Group Squalene and cholesterol synthesis at 0x307d14550>,
 <Group Sink at 0x307d153d0>]

In [2]:
model.metabolites

NameError: name 'model' is not defined

In [6]:
import mygene

# Initialize MyGeneInfo
mg = mygene.MyGeneInfo()

# Example numerical IDs
numerical_ids = ["7157", "1029"]  # Replace with your gene IDs

# Query MyGene.info
gene_info = mg.querymany(numerical_ids, scopes='entrezgene', fields='symbol', species='human')

# Print gene names
for gene in gene_info:
    print(gene['query'], gene.get('symbol'))

1 input query terms found no hit:	['7157.1']

7157.1 None
1029 CDKN2A

In [12]:
from cobra.flux_analysis import double_gene_deletion

In [15]:
model.genes.get_by_id('26.1').summary()

AttributeError: 'Gene' object has no attribute 'summary'